// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAU6pVg1gVtrtWoT7FF6sm3awprwKf1rQ',
    appId: '1:429230748709:web:faf82f409d1aa892a6bbcc',
    messagingSenderId: '429230748709',
    projectId: 'foster-ulcer-ai',
    authDomain: 'foster-ulcer-ai.firebaseapp.com',
    storageBucket: 'foster-ulcer-ai.firebasestorage.app',
    measurementId: 'G-J85457SWY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnCANLhBBnJabG1LS_WfyTHkrPvxN2N-M',
    appId: '1:429230748709:android:38f6c676835d25e5a6bbcc',
    messagingSenderId: '429230748709',
    projectId: 'foster-ulcer-ai',
    storageBucket: 'foster-ulcer-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQZwXqfT7vlyMrr9dh5EZzW9NjycBPBdA',
    appId: '1:429230748709:ios:b3a341d764bd7622a6bbcc',
    messagingSenderId: '429230748709',
    projectId: 'foster-ulcer-ai',
    storageBucket: 'foster-ulcer-ai.firebasestorage.app',
    iosBundleId: 'com.example.fosterUlcerAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQZwXqfT7vlyMrr9dh5EZzW9NjycBPBdA',
    appId: '1:429230748709:ios:b3a341d764bd7622a6bbcc',
    messagingSenderId: '429230748709',
    projectId: 'foster-ulcer-ai',
    storageBucket: 'foster-ulcer-ai.firebasestorage.app',
    iosBundleId: 'com.example.fosterUlcerAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAU6pVg1gVtrtWoT7FF6sm3awprwKf1rQ',
    appId: '1:429230748709:web:ec4ae13e4b6b6fd3a6bbcc',
    messagingSenderId: '429230748709',
    projectId: 'foster-ulcer-ai',
    authDomain: 'foster-ulcer-ai.firebaseapp.com',
    storageBucket: 'foster-ulcer-ai.firebasestorage.app',
    measurementId: 'G-ZMDKKQ02TV',
  );
}
